- name: POST Delete transactions
  uri:
    url: "https://{{ provider.server }}{{ restBashUrl }}"
    method: POST
    headers:
      X-F5-Auth-Token: "{{ token.json.token.token }}"
    return_content: true
    validate_certs: false
    body_format: json
    body: | 
        {
        "command": "run",
        "utilCmdArgs": "-c \' echo -e \' delete cli transaction\' | tmsh -q\'"
        }
    status_code: 202, 200
  register: policyResult
  delegate_to: localhost

- debug:
    msg: "{{policyResult}}"