- name: get auth token
  uri:
    url: "https://{{ bigiq.host }}{{ authUrl }}"
    method: POST
    body_format: json
    return_content: true
    validate_certs: false
    body: {"username":"{{ bigiq.user }}","password":"{{ bigiq.password }}","loginProviderName":"tmos"}
    status_code: 200
  register: token
  retries: 3
  delay: 30
  delegate_to: localhost