- name: check for DO
  uri: 
    url: "https://{{ provider.server }}{{ doUrl }}"
    method: GET
    headers:
      X-F5-Auth-Token: "{{ token.json.token.token }}"
    return_content: true
    validate_certs: false
    status_code: 200
  register: do_check
  until: do_check is success
  retries: 6
  delay: 60
  delegate_to: localhost
  when: token.json.token.token != ""
