- name: check for AS3
  uri: 
    url: "https://{{ provider.server }}{{ as3CheckUrl }}"
    method: GET
    headers:
      X-F5-Auth-Token: "{{ token.json.token.token }}"
    return_content: true
    validate_certs: false
    status_code: 200
  register: as3_check
  until: as3_check is success
  retries: 6
  delay: 60
  delegate_to: localhost
  when: token.json.token.token != ""

# - name: debug check as3_check
#   debug:
#     msg: "{{as3_check}}"