---
# tasks file for f5-atc

- import_tasks: get_rpms.yml
- import_tasks: status.yml
- import_tasks: auth.yml
- import_tasks: upload.yml
- import_tasks: install_wsl.yml
  when: wsl
- import_tasks: install.yml
  when: not wsl
- import_tasks: status.yml
# - import_tasks: wait_as3.yml
- import_tasks: check_do.yml
- import_tasks: check_ts.yml
- import_tasks: check_as3.yml
- import_tasks: status.yml



