---
# vars file for f5-bigiq-as3
filePath: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}"

authUrl: "/mgmt/shared/authn/login"
provider.server: "{{ovaResult.instance.ipv4}}"
as3CheckUrl: "/mgmt/shared/appsvcs/info"



# as3
as3Url: "/mgmt/shared/appsvcs/declare"
as3List: "{{ lookup('vars', 'context.as3.apps', default=provider.as3.apps)}}"

# do
doUrl: "/mgmt/shared/declarative-onboarding"
doCheckUrl: "/mgmt/shared/declarative-onboarding/available"


# ts
tsUrl: "/mgmt/shared/telemetry/declare"
tsCheckUrl: "/mgmt/shared/telemetry/available"